## What is pytorch

+ a replacement for Numpy to use the power of GPUs
+ a deep learning research platform that provides maximum flexibility and speed

### Tensor

In [2]:
from __future__ import print_function
import torch

In [3]:
x = torch.ones(4,4)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [4]:
x = (torch.triu(x) == 1).transpose(0,1)

In [5]:
x

tensor([[ True, False, False, False],
        [ True,  True, False, False],
        [ True,  True,  True, False],
        [ True,  True,  True,  True]])

In [6]:
x = x.float().masked_fill(x == 0, float("-inf")).masked_fill(x == 1, float(0.0))

In [7]:
x

tensor([[0., -inf, -inf, -inf],
        [0., 0., -inf, -inf],
        [0., 0., 0., -inf],
        [0., 0., 0., 0.]])

In [8]:
x = torch.rand(5,3)
print(x)

tensor([[0.2383, 0.7144, 0.7971],
        [0.7670, 0.0398, 0.3647],
        [0.6130, 0.2041, 0.8209],
        [0.5139, 0.7664, 0.3357],
        [0.8299, 0.6448, 0.5143]])


In [4]:
x = torch.zeros(5,3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [34]:
x = x.new_ones(5,3, dtype = torch.double)
print(x)
x = torch.randn_like(x, dtype = torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.7367,  0.4018,  1.2512],
        [-0.8627,  0.9114,  0.0673],
        [-1.0572,  1.1934, -0.3611],
        [-0.0311, -0.7293, -2.9331],
        [ 1.1302, -0.3819, -1.8125]])


In [35]:
print(x.size())

torch.Size([5, 3])


### Operation

#### 1. Addition

In [8]:
y = torch.rand(5,3)
print(x+y)

tensor([[ 0.3387,  1.0256,  1.3628],
        [ 0.6140,  1.7874, -0.1236],
        [ 1.0419,  0.9883,  1.2679],
        [ 1.0119,  2.0772,  0.9040],
        [ 0.4989,  2.6630, -0.3574]])


In [39]:
x

tensor([[-1.7367,  0.4018,  1.2512],
        [-0.8627,  0.9114,  0.0673],
        [-1.0572,  1.1934, -0.3611],
        [-0.0311, -0.7293, -2.9331],
        [ 1.1302, -0.3819, -1.8125]])

In [47]:
y = torch.ones(1,3)
y

tensor([[1., 1., 1.]])

In [48]:
x+y

tensor([[-0.7367,  1.4018,  2.2512],
        [ 0.1373,  1.9114,  1.0673],
        [-0.0572,  2.1934,  0.6389],
        [ 0.9689,  0.2707, -1.9331],
        [ 2.1302,  0.6181, -0.8125]])

In [49]:
print(torch.add(x,y))

tensor([[-0.7367,  1.4018,  2.2512],
        [ 0.1373,  1.9114,  1.0673],
        [-0.0572,  2.1934,  0.6389],
        [ 0.9689,  0.2707, -1.9331],
        [ 2.1302,  0.6181, -0.8125]])


In [50]:
result = torch.empty(5,3)
torch.add(x, y, out = result)
print(result)

tensor([[-0.7367,  1.4018,  2.2512],
        [ 0.1373,  1.9114,  1.0673],
        [-0.0572,  2.1934,  0.6389],
        [ 0.9689,  0.2707, -1.9331],
        [ 2.1302,  0.6181, -0.8125]])


In [11]:
y.add_(x)  ## add 뒤에 _가 붙었다는 사실 주의. _가 붙으면 y값이 바뀐다. 
print(y)

tensor([[ 0.3387,  1.0256,  1.3628],
        [ 0.6140,  1.7874, -0.1236],
        [ 1.0419,  0.9883,  1.2679],
        [ 1.0119,  2.0772,  0.9040],
        [ 0.4989,  2.6630, -0.3574]])


In [14]:
print(x[:,1])

tensor([0.3245, 0.8762, 0.2162, 2.0708, 1.8158])


#### 2. resizing

In [54]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8 ,2)  # the size -1 is inferred from other dimensions

print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([1, 8, 2])


In [18]:
print(z)

tensor([[ 1.8857, -0.7636, -0.5458, -0.5823, -0.1834,  1.7325,  0.0351, -0.9221],
        [ 0.4462,  0.9983,  0.0037,  2.0293, -0.8469, -0.3382, -1.0415,  0.9273]])


In [20]:
x = torch.randn(1)
print(x)
print(x.item())   #use .item() method to get the value as a python number

tensor([-1.9769])
-1.9768799543380737


### for more info: [pytorch documentation](https://pytorch.org/docs/torch)

### Numpy Bridge

In [9]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [10]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [11]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### Converting Numpy array to Torch Tensor

In [13]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out = a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [14]:
torch.cuda.is_available()

False

### CUDA Tensors
+ Tensors can be moved onto any device using the .to method

```python 
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device = device) #directly create a tensor on GPU
    x = x.to(device)                        #or just use strings to("cuda")
    z = x+y
    print(z)
    print(z.to('cpu', torch.double))```