## Autograd: Automatic Differentiation

autograd package provides:
+ automatic differentiation for all operations on Tensors
+ a define-by-run framework
+ your backprop is defined by how your code is run, and that every single iteration can be different

### Tensor

+ requires_grad == True 이면 모든 연산을 추적한다
+ .backward() : have all the gradients computed automatically
+ .grad : into which the gradient for this tensor will be accumulated
+ .detach() : stop a tensor from tracking history

+ with torch.no_grad(): prevent tracking history (and using memeory)
+ .backward() : compute the derivatives
    + if Tensor is not a scalar, .backward() needs a gradient argument that is a tensor of matching shape


### Function

+ Tensor and Function are interconnected and build up an acyclic graph, that encodes a complete history of computation. 
+ grad_fn : references a Funtion that has created the Tensor (except for Tensor created by the user)

In [1]:
import torch

x = torch.ones(2, 2, requires_grad = True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [2]:
y = x + 2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [3]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [7]:
# how to change requires_grad attribute

a = torch.randn(2,2)
a = ((a*3) / (a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)

False
True


In [8]:
out.backward() #backprop

In [10]:
print(x.grad) # 

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [27]:
print(y)
print(y.data)
print(y.data.norm(1))

tensor([ -479.2729, -1039.9626,  -900.8378], grad_fn=<MulBackward0>)
tensor([ -479.2729, -1039.9626,  -900.8378])
tensor(2420.0732)


In [12]:
x = torch.randn(3, requires_grad = True)
print(x)
y = x*2
while y.data.norm()<1000:
    y = y*2
print(y)

tensor([-0.9361, -2.0312, -1.7594], requires_grad=True)
tensor([ -479.2729, -1039.9626,  -900.8378], grad_fn=<MulBackward0>)


In [13]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype = torch.float)
y.backward(v)
print(x.grad)

tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


In [14]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
